export const SERVICE_UNITS = [
  "kilogram",
  "gram",
  "milligram",
  "litre",
  "milliliter",
  "centimeter",
  "meter",
  "kilometer",
  "mile",
  "inch",
  "foot",
  "ton",
  "pound",
  "lessons",
  "sessions",
  "movies",
  //"seconds",
  "minutes",
  "hours",
  "days",
  "weeks",
  "months",
  "years",
];

export const PAYMENT_EVENTS = {
  AUTHORIZED: "payment.authorized",
  CAPTURED: "payment.captured",
  FAILED: "payment.failed",
  REFUNDED: "payment.refunded",
};

export const COUNTRY_CURRENCY_PHONE_CODE = [
  {
    id: "1",
    country_name: "Afghanistan",
    country_code: "AF",
    dial_code: "+93",
    currency_name: null,
    currency_code: "AFN",
    currency_symbol: null,
  },
  {
    id: "2",
    country_name: "Albania",
    country_code: "AL",
    dial_code: "+355",
    currency_name: null,
    currency_code: "ALL",
    currency_symbol: null,
  },
  {
    id: "3",
    country_name: "Algeria",
    country_code: "DZ",
    dial_code: "+213",
    currency_name: null,
    currency_code: "DZD",
    currency_symbol: null,
  },
  {
    id: "4",
    country_name: "American Samoa",
    country_code: "AS",
    dial_code: "+1684",
    currency_name: null,
    currency_code: "USD",
    currency_symbol: null,
  },
  {
    id: "5",
    country_name: "Andorra",
    country_code: "AD",
    dial_code: "+376",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "6",
    country_name: "Angola",
    country_code: "AO",
    dial_code: "+244",
    currency_name: null,
    currency_code: "AOA",
    currency_symbol: null,
  },
  {
    id: "7",
    country_name: "Anguilla",
    country_code: "AI",
    dial_code: "+1264",
    currency_name: null,
    currency_code: "XCD",
    currency_symbol: null,
  },
  {
    id: "8",
    country_name: "Antarctica",
    country_code: "AQ",
    dial_code: "+672",
    currency_name: null,
    currency_code: "XCD",
    currency_symbol: null,
  },
  {
    id: "9",
    country_name: "Antigua and Barbuda",
    country_code: "AG",
    dial_code: "+1268",
    currency_name: null,
    currency_code: "XCD",
    currency_symbol: null,
  },
  {
    id: "10",
    country_name: "Argentina",
    country_code: "AR",
    dial_code: "+54",
    currency_name: null,
    currency_code: "ARS",
    currency_symbol: null,
  },
  {
    id: "11",
    country_name: "Armenia",
    country_code: "AM",
    dial_code: "+374",
    currency_name: null,
    currency_code: "AMD",
    currency_symbol: null,
  },
  {
    id: "12",
    country_name: "Aruba",
    country_code: "AW",
    dial_code: "+297",
    currency_name: null,
    currency_code: "AWG",
    currency_symbol: null,
  },
  {
    id: "13",
    country_name: "Australia",
    country_code: "AU",
    dial_code: "+61",
    currency_name: null,
    currency_code: "AUD",
    currency_symbol: null,
  },
  {
    id: "14",
    country_name: "Austria",
    country_code: "AT",
    dial_code: "+43",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "15",
    country_name: "Azerbaijan",
    country_code: "AZ",
    dial_code: "+994",
    currency_name: null,
    currency_code: "AZN",
    currency_symbol: null,
  },
  {
    id: "16",
    country_name: "Bahamas",
    country_code: "BS",
    dial_code: "+1242",
    currency_name: null,
    currency_code: "BSD",
    currency_symbol: null,
  },
  {
    id: "17",
    country_name: "Bahrain",
    country_code: "BH",
    dial_code: "+973",
    currency_name: null,
    currency_code: "BHD",
    currency_symbol: null,
  },
  {
    id: "18",
    country_name: "Bangladesh",
    country_code: "BD",
    dial_code: "+880",
    currency_name: null,
    currency_code: "BDT",
    currency_symbol: null,
  },
  {
    id: "19",
    country_name: "Barbados",
    country_code: "BB",
    dial_code: "+1246",
    currency_name: null,
    currency_code: "BBD",
    currency_symbol: null,
  },
  {
    id: "20",
    country_name: "Belarus",
    country_code: "BY",
    dial_code: "+375",
    currency_name: null,
    currency_code: "BYR",
    currency_symbol: null,
  },
  {
    id: "21",
    country_name: "Belgium",
    country_code: "BE",
    dial_code: "+32",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "22",
    country_name: "Belize",
    country_code: "BZ",
    dial_code: "+501",
    currency_name: null,
    currency_code: "BZD",
    currency_symbol: null,
  },
  {
    id: "23",
    country_name: "Benin",
    country_code: "BJ",
    dial_code: "+229",
    currency_name: null,
    currency_code: "XOF",
    currency_symbol: null,
  },
  {
    id: "24",
    country_name: "Bermuda",
    country_code: "BM",
    dial_code: "+1441",
    currency_name: null,
    currency_code: "BMD",
    currency_symbol: null,
  },
  {
    id: "25",
    country_name: "Bhutan",
    country_code: "BT",
    dial_code: "+975",
    currency_name: null,
    currency_code: "BTN",
    currency_symbol: null,
  },
  {
    id: "26",
    country_name: "Bolivia, Plurinational State of Bolivia",
    country_code: "BO",
    dial_code: "+591",
    currency_name: null,
    currency_code: "BOB",
    currency_symbol: null,
  },
  {
    id: "27",
    country_name: "Bosnia and Herzegovina",
    country_code: "BA",
    dial_code: "+387",
    currency_name: null,
    currency_code: "BAM",
    currency_symbol: null,
  },
  {
    id: "28",
    country_name: "Botswana",
    country_code: "BW",
    dial_code: "+267",
    currency_name: null,
    currency_code: "BWP",
    currency_symbol: null,
  },
  {
    id: "29",
    country_name: "Bouvet Island",
    country_code: "BV",
    dial_code: "+55",
    currency_name: null,
    currency_code: "NOK",
    currency_symbol: null,
  },
  {
    id: "30",
    country_name: "Brazil",
    country_code: "BR",
    dial_code: "+55",
    currency_name: null,
    currency_code: "BRL",
    currency_symbol: null,
  },
  {
    id: "31",
    country_name: "British Indian Ocean Territory",
    country_code: "IO",
    dial_code: "+246",
    currency_name: null,
    currency_code: "USD",
    currency_symbol: null,
  },
  {
    id: "32",
    country_name: "Brunei Darussalam",
    country_code: "BN",
    dial_code: "+673",
    currency_name: null,
    currency_code: "BND",
    currency_symbol: null,
  },
  {
    id: "33",
    country_name: "Bulgaria",
    country_code: "BG",
    dial_code: "+359",
    currency_name: null,
    currency_code: "BGN",
    currency_symbol: null,
  },
  {
    id: "34",
    country_name: "Burkina Faso",
    country_code: "BF",
    dial_code: "+226",
    currency_name: null,
    currency_code: "XOF",
    currency_symbol: null,
  },
  {
    id: "35",
    country_name: "Burundi",
    country_code: "BI",
    dial_code: "+257",
    currency_name: null,
    currency_code: "BIF",
    currency_symbol: null,
  },
  {
    id: "36",
    country_name: "Cambodia",
    country_code: "KH",
    dial_code: "+855",
    currency_name: null,
    currency_code: "KHR",
    currency_symbol: null,
  },
  {
    id: "37",
    country_name: "Cameroon",
    country_code: "CM",
    dial_code: "+237",
    currency_name: null,
    currency_code: "XAF",
    currency_symbol: null,
  },
  {
    id: "38",
    country_name: "Canada",
    country_code: "CA",
    dial_code: "+1",
    currency_name: null,
    currency_code: "CAD",
    currency_symbol: null,
  },
  {
    id: "39",
    country_name: "Cape Verde",
    country_code: "CV",
    dial_code: "+238",
    currency_name: null,
    currency_code: "CVE",
    currency_symbol: null,
  },
  {
    id: "40",
    country_name: "Cayman Islands",
    country_code: "KY",
    dial_code: "+1345",
    currency_name: null,
    currency_code: "KYD",
    currency_symbol: null,
  },
  {
    id: "41",
    country_name: "Central African Republic",
    country_code: "CF",
    dial_code: "+236",
    currency_name: null,
    currency_code: "XAF",
    currency_symbol: null,
  },
  {
    id: "42",
    country_name: "Chad",
    country_code: "TD",
    dial_code: "+235",
    currency_name: null,
    currency_code: "XAF",
    currency_symbol: null,
  },
  {
    id: "43",
    country_name: "Chile",
    country_code: "CL",
    dial_code: "+56",
    currency_name: null,
    currency_code: "CLP",
    currency_symbol: null,
  },
  {
    id: "44",
    country_name: "China",
    country_code: "CN",
    dial_code: "+86",
    currency_name: null,
    currency_code: "CNY",
    currency_symbol: null,
  },
  {
    id: "45",
    country_name: "Christmas Island",
    country_code: "CX",
    dial_code: "+61",
    currency_name: null,
    currency_code: "AUD",
    currency_symbol: null,
  },
  {
    id: "46",
    country_name: "Cocos (Keeling) Islands",
    country_code: "CC",
    dial_code: "+61",
    currency_name: null,
    currency_code: "AUD",
    currency_symbol: null,
  },
  {
    id: "47",
    country_name: "Colombia",
    country_code: "CO",
    dial_code: "+57",
    currency_name: null,
    currency_code: "COP",
    currency_symbol: null,
  },
  {
    id: "48",
    country_name: "Comoros",
    country_code: "KM",
    dial_code: "+269",
    currency_name: null,
    currency_code: "KMF",
    currency_symbol: null,
  },
  {
    id: "49",
    country_name: "Congo",
    country_code: "CG",
    dial_code: "+242",
    currency_name: null,
    currency_code: "XAF",
    currency_symbol: null,
  },
  {
    id: "50",
    country_name: "Congo, The Democratic Republic of",
    country_code: "CD",
    dial_code: "+243",
    currency_name: null,
    currency_code: "CDF",
    currency_symbol: null,
  },
  {
    id: "51",
    country_name: "Cook Islands",
    country_code: "CK",
    dial_code: "+682",
    currency_name: null,
    currency_code: "NZD",
    currency_symbol: null,
  },
  {
    id: "52",
    country_name: "Costa Rica",
    country_code: "CR",
    dial_code: "+506",
    currency_name: null,
    currency_code: "CRC",
    currency_symbol: null,
  },
  {
    id: "53",
    country_name: "Croatia",
    country_code: "HR",
    dial_code: "+385",
    currency_name: null,
    currency_code: "HRK",
    currency_symbol: null,
  },
  {
    id: "54",
    country_name: "Cuba",
    country_code: "CU",
    dial_code: "+53",
    currency_name: null,
    currency_code: "CUP",
    currency_symbol: null,
  },
  {
    id: "55",
    country_name: "Cyprus",
    country_code: "CY",
    dial_code: "+357",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "56",
    country_name: "Czech Republic",
    country_code: "CZ",
    dial_code: "+420",
    currency_name: null,
    currency_code: "CZK",
    currency_symbol: null,
  },
  {
    id: "57",
    country_name: "Denmark",
    country_code: "DK",
    dial_code: "+45",
    currency_name: null,
    currency_code: "DKK",
    currency_symbol: null,
  },
  {
    id: "58",
    country_name: "Djibouti",
    country_code: "DJ",
    dial_code: "+253",
    currency_name: null,
    currency_code: "DJF",
    currency_symbol: null,
  },
  {
    id: "59",
    country_name: "Dominica",
    country_code: "DM",
    dial_code: "+1767",
    currency_name: null,
    currency_code: "XCD",
    currency_symbol: null,
  },
  {
    id: "60",
    country_name: "Dominican Republic",
    country_code: "DO",
    dial_code: "+1849",
    currency_name: null,
    currency_code: "DOP",
    currency_symbol: null,
  },
  {
    id: "61",
    country_name: "Ecuador",
    country_code: "EC",
    dial_code: "+593",
    currency_name: null,
    currency_code: "ECS",
    currency_symbol: null,
  },
  {
    id: "62",
    country_name: "Egypt",
    country_code: "EG",
    dial_code: "+20",
    currency_name: null,
    currency_code: "EGP",
    currency_symbol: null,
  },
  {
    id: "63",
    country_name: "El Salvador",
    country_code: "SV",
    dial_code: "+503",
    currency_name: null,
    currency_code: "SVC",
    currency_symbol: null,
  },
  {
    id: "64",
    country_name: "Equatorial Guinea",
    country_code: "GQ",
    dial_code: "+240",
    currency_name: null,
    currency_code: "XAF",
    currency_symbol: null,
  },
  {
    id: "65",
    country_name: "Eritrea",
    country_code: "ER",
    dial_code: "+291",
    currency_name: null,
    currency_code: "ERN",
    currency_symbol: null,
  },
  {
    id: "66",
    country_name: "Estonia",
    country_code: "EE",
    dial_code: "+372",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "67",
    country_name: "Ethiopia",
    country_code: "ET",
    dial_code: "+251",
    currency_name: null,
    currency_code: "ETB",
    currency_symbol: null,
  },
  {
    id: "68",
    country_name: "Falkland Islands (Malvinas)",
    country_code: "FK",
    dial_code: "+500",
    currency_name: null,
    currency_code: "FKP",
    currency_symbol: null,
  },
  {
    id: "69",
    country_name: "Faroe Islands",
    country_code: "FO",
    dial_code: "+298",
    currency_name: null,
    currency_code: "DKK",
    currency_symbol: null,
  },
  {
    id: "70",
    country_name: "Fiji",
    country_code: "FJ",
    dial_code: "+679",
    currency_name: null,
    currency_code: "FJD",
    currency_symbol: null,
  },
  {
    id: "71",
    country_name: "Finland",
    country_code: "FI",
    dial_code: "+358",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "72",
    country_name: "France",
    country_code: "FR",
    dial_code: "+33",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "73",
    country_name: "French Guiana",
    country_code: "GF",
    dial_code: "+594",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "74",
    country_name: "French Polynesia",
    country_code: "PF",
    dial_code: "+689",
    currency_name: null,
    currency_code: "XPF",
    currency_symbol: null,
  },
  {
    id: "75",
    country_name: "French Southern and Antarctic Lands",
    country_code: "TF",
    dial_code: "+262",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "76",
    country_name: "Gabon",
    country_code: "GA",
    dial_code: "+241",
    currency_name: null,
    currency_code: "XAF",
    currency_symbol: null,
  },
  {
    id: "77",
    country_name: "Gambia",
    country_code: "GM",
    dial_code: "+220",
    currency_name: null,
    currency_code: "GMD",
    currency_symbol: null,
  },
  {
    id: "78",
    country_name: "Georgia",
    country_code: "GE",
    dial_code: "+995",
    currency_name: null,
    currency_code: "GEL",
    currency_symbol: null,
  },
  {
    id: "79",
    country_name: "Germany",
    country_code: "DE",
    dial_code: "+49",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "80",
    country_name: "Ghana",
    country_code: "GH",
    dial_code: "+233",
    currency_name: null,
    currency_code: "GHS",
    currency_symbol: null,
  },
  {
    id: "81",
    country_name: "Gibraltar",
    country_code: "GI",
    dial_code: "+350",
    currency_name: null,
    currency_code: "GIP",
    currency_symbol: null,
  },
  {
    id: "82",
    country_name: "Greece",
    country_code: "GR",
    dial_code: "+30",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "83",
    country_name: "Greenland",
    country_code: "GL",
    dial_code: "+299",
    currency_name: null,
    currency_code: "DKK",
    currency_symbol: null,
  },
  {
    id: "84",
    country_name: "Grenada",
    country_code: "GD",
    dial_code: "+1473",
    currency_name: null,
    currency_code: "XCD",
    currency_symbol: null,
  },
  {
    id: "85",
    country_name: "Guadeloupe",
    country_code: "GP",
    dial_code: "+590",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "86",
    country_name: "Guam",
    country_code: "GU",
    dial_code: "+1671",
    currency_name: null,
    currency_code: "USD",
    currency_symbol: null,
  },
  {
    id: "87",
    country_name: "Guatemala",
    country_code: "GT",
    dial_code: "+502",
    currency_name: null,
    currency_code: "QTQ",
    currency_symbol: null,
  },
  {
    id: "88",
    country_name: "Guernsey",
    country_code: "GG",
    dial_code: "+44",
    currency_name: null,
    currency_code: "GGP",
    currency_symbol: null,
  },
  {
    id: "89",
    country_name: "Guinea",
    country_code: "GN",
    dial_code: "+224",
    currency_name: null,
    currency_code: "GNF",
    currency_symbol: null,
  },
  {
    id: "90",
    country_name: "Guinea-Bissau",
    country_code: "GW",
    dial_code: "+245",
    currency_name: null,
    currency_code: "CFA",
    currency_symbol: null,
  },
  {
    id: "91",
    country_name: "Guyana",
    country_code: "GY",
    dial_code: "+592",
    currency_name: null,
    currency_code: "GYD",
    currency_symbol: null,
  },
  {
    id: "92",
    country_name: "Haiti",
    country_code: "HT",
    dial_code: "+509",
    currency_name: null,
    currency_code: "HTG",
    currency_symbol: null,
  },
  {
    id: "93",
    country_name: "Heard Island and McDonald Islands",
    country_code: "HM",
    dial_code: "+672",
    currency_name: null,
    currency_code: "AUD",
    currency_symbol: null,
  },
  {
    id: "94",
    country_name: "Holy See (Vatican City State)",
    country_code: "VA",
    dial_code: "+379",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "95",
    country_name: "Honduras",
    country_code: "HN",
    dial_code: "+504",
    currency_name: null,
    currency_code: "HNL",
    currency_symbol: null,
  },
  {
    id: "96",
    country_name: "Hong Kong",
    country_code: "HK",
    dial_code: "+852",
    currency_name: null,
    currency_code: "HKD",
    currency_symbol: null,
  },
  {
    id: "97",
    country_name: "Hungary",
    country_code: "HU",
    dial_code: "+36",
    currency_name: null,
    currency_code: "HUF",
    currency_symbol: null,
  },
  {
    id: "98",
    country_name: "Iceland",
    country_code: "IS",
    dial_code: "+354",
    currency_name: null,
    currency_code: "ISK",
    currency_symbol: null,
  },
  {
    id: "99",
    country_name: "India",
    country_code: "IN",
    dial_code: "+91",
    currency_name: null,
    currency_code: "INR",
    currency_symbol: null,
  },
  {
    id: "100",
    country_name: "Indonesia",
    country_code: "ID",
    dial_code: "+62",
    currency_name: null,
    currency_code: "IDR",
    currency_symbol: null,
  },
  {
    id: "101",
    country_name: "Iran, Islamic Republic of",
    country_code: "IR",
    dial_code: "+98",
    currency_name: null,
    currency_code: "IRR",
    currency_symbol: null,
  },
  {
    id: "102",
    country_name: "Iraq",
    country_code: "IQ",
    dial_code: "+964",
    currency_name: null,
    currency_code: "IQD",
    currency_symbol: null,
  },
  {
    id: "103",
    country_name: "Ireland",
    country_code: "IE",
    dial_code: "+353",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "104",
    country_name: "Isle of Man",
    country_code: "IM",
    dial_code: "+44",
    currency_name: null,
    currency_code: "IMP",
    currency_symbol: null,
  },
  {
    id: "105",
    country_name: "Israel",
    country_code: "IL",
    dial_code: "+972",
    currency_name: null,
    currency_code: "ILS",
    currency_symbol: null,
  },
  {
    id: "106",
    country_name: "Italy",
    country_code: "IT",
    dial_code: "+39",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "107",
    country_name: "Ivory Coast (Cote d'Ivoire)",
    country_code: "CI",
    dial_code: "+225",
    currency_name: null,
    currency_code: "XOF",
    currency_symbol: null,
  },
  {
    id: "108",
    country_name: "Jamaica",
    country_code: "JM",
    dial_code: "+1876",
    currency_name: null,
    currency_code: "JMD",
    currency_symbol: null,
  },
  {
    id: "109",
    country_name: "Japan",
    country_code: "JP",
    dial_code: "+81",
    currency_name: null,
    currency_code: "JPY",
    currency_symbol: null,
  },
  {
    id: "110",
    country_name: "Jersey",
    country_code: "JE",
    dial_code: "+44",
    currency_name: null,
    currency_code: "GBP",
    currency_symbol: null,
  },
  {
    id: "111",
    country_name: "Jordan",
    country_code: "JO",
    dial_code: "+962",
    currency_name: null,
    currency_code: "JOD",
    currency_symbol: null,
  },
  {
    id: "112",
    country_name: "Kazakhstan",
    country_code: "KZ",
    dial_code: "+7",
    currency_name: null,
    currency_code: "KZT",
    currency_symbol: null,
  },
  {
    id: "113",
    country_name: "Kenya",
    country_code: "KE",
    dial_code: "+254",
    currency_name: null,
    currency_code: "KES",
    currency_symbol: null,
  },
  {
    id: "114",
    country_name: "Kiribati",
    country_code: "KI",
    dial_code: "+686",
    currency_name: null,
    currency_code: "AUD",
    currency_symbol: null,
  },
  {
    id: "115",
    country_name: "Kuwait",
    country_code: "KW",
    dial_code: "+965",
    currency_name: null,
    currency_code: "KWD",
    currency_symbol: null,
  },
  {
    id: "116",
    country_name: "Kyrgyzstan",
    country_code: "KG",
    dial_code: "+996",
    currency_name: null,
    currency_code: "KGS",
    currency_symbol: null,
  },
  {
    id: "117",
    country_name: "Lao People's Democratic Republic",
    country_code: "LA",
    dial_code: "+856",
    currency_name: null,
    currency_code: "LAK",
    currency_symbol: null,
  },
  {
    id: "118",
    country_name: "Latvia",
    country_code: "LV",
    dial_code: "+371",
    currency_name: null,
    currency_code: "LVL",
    currency_symbol: null,
  },
  {
    id: "119",
    country_name: "Lebanon",
    country_code: "LB",
    dial_code: "+961",
    currency_name: null,
    currency_code: "LBP",
    currency_symbol: null,
  },
  {
    id: "120",
    country_name: "Lesotho",
    country_code: "LS",
    dial_code: "+266",
    currency_name: null,
    currency_code: "LSL",
    currency_symbol: null,
  },
  {
    id: "121",
    country_name: "Liberia",
    country_code: "LR",
    dial_code: "+231",
    currency_name: null,
    currency_code: "LRD",
    currency_symbol: null,
  },
  {
    id: "122",
    country_name: "Libyan Arab Jamahiriya",
    country_code: "LY",
    dial_code: "+218",
    currency_name: null,
    currency_code: "LYD",
    currency_symbol: null,
  },
  {
    id: "123",
    country_name: "Liechtenstein",
    country_code: "LI",
    dial_code: "+423",
    currency_name: null,
    currency_code: "CHF",
    currency_symbol: null,
  },
  {
    id: "124",
    country_name: "Lithuania",
    country_code: "LT",
    dial_code: "+370",
    currency_name: null,
    currency_code: "LTL",
    currency_symbol: null,
  },
  {
    id: "125",
    country_name: "Luxembourg",
    country_code: "LU",
    dial_code: "+352",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "126",
    country_name: "Macao",
    country_code: "MO",
    dial_code: "+853",
    currency_name: null,
    currency_code: "MOP",
    currency_symbol: null,
  },
  {
    id: "127",
    country_name: "Macedonia, The Former Yugoslav Republic of",
    country_code: "MK",
    dial_code: "+389",
    currency_name: null,
    currency_code: "MKD",
    currency_symbol: null,
  },
  {
    id: "128",
    country_name: "Madagascar",
    country_code: "MG",
    dial_code: "+261",
    currency_name: null,
    currency_code: "MGF",
    currency_symbol: null,
  },
  {
    id: "129",
    country_name: "Malawi",
    country_code: "MW",
    dial_code: "+265",
    currency_name: null,
    currency_code: "MWK",
    currency_symbol: null,
  },
  {
    id: "130",
    country_name: "Malaysia",
    country_code: "MY",
    dial_code: "+60",
    currency_name: null,
    currency_code: "MYR",
    currency_symbol: null,
  },
  {
    id: "131",
    country_name: "Maldives",
    country_code: "MV",
    dial_code: "+960",
    currency_name: null,
    currency_code: "MVR",
    currency_symbol: null,
  },
  {
    id: "132",
    country_name: "Mali",
    country_code: "ML",
    dial_code: "+223",
    currency_name: null,
    currency_code: "XOF",
    currency_symbol: null,
  },
  {
    id: "133",
    country_name: "Malta",
    country_code: "MT",
    dial_code: "+356",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "134",
    country_name: "Marshall Islands",
    country_code: "MH",
    dial_code: "+692",
    currency_name: null,
    currency_code: "USD",
    currency_symbol: null,
  },
  {
    id: "135",
    country_name: "Martinique",
    country_code: "MQ",
    dial_code: "+596",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "136",
    country_name: "Mauritania",
    country_code: "MR",
    dial_code: "+222",
    currency_name: null,
    currency_code: "MRO",
    currency_symbol: null,
  },
  {
    id: "137",
    country_name: "Mauritius",
    country_code: "MU",
    dial_code: "+230",
    currency_name: null,
    currency_code: "MUR",
    currency_symbol: null,
  },
  {
    id: "138",
    country_name: "Mayotte",
    country_code: "YT",
    dial_code: "+262",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "139",
    country_name: "Mexico",
    country_code: "MX",
    dial_code: "+52",
    currency_name: null,
    currency_code: "MXN",
    currency_symbol: null,
  },
  {
    id: "140",
    country_name: "Micronesia, Federated States of",
    country_code: "FM",
    dial_code: "+691",
    currency_name: null,
    currency_code: "USD",
    currency_symbol: null,
  },
  {
    id: "141",
    country_name: "Moldova, Republic of",
    country_code: "MD",
    dial_code: "+373",
    currency_name: null,
    currency_code: "MDL",
    currency_symbol: null,
  },
  {
    id: "142",
    country_name: "Monaco",
    country_code: "MC",
    dial_code: "+377",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "143",
    country_name: "Mongolia",
    country_code: "MN",
    dial_code: "+976",
    currency_name: null,
    currency_code: "MNT",
    currency_symbol: null,
  },
  {
    id: "144",
    country_name: "Montenegro",
    country_code: "ME",
    dial_code: "+382",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "145",
    country_name: "Montserrat",
    country_code: "MS",
    dial_code: "+1664",
    currency_name: null,
    currency_code: "XCD",
    currency_symbol: null,
  },
  {
    id: "146",
    country_name: "Morocco",
    country_code: "MA",
    dial_code: "+212",
    currency_name: null,
    currency_code: "MAD",
    currency_symbol: null,
  },
  {
    id: "147",
    country_name: "Mozambique",
    country_code: "MZ",
    dial_code: "+258",
    currency_name: null,
    currency_code: "MZN",
    currency_symbol: null,
  },
  {
    id: "148",
    country_name: "Myanmar",
    country_code: "MM",
    dial_code: "+95",
    currency_name: null,
    currency_code: "MMR",
    currency_symbol: null,
  },
  {
    id: "149",
    country_name: "Namibia",
    country_code: "NA",
    dial_code: "+264",
    currency_name: null,
    currency_code: "NAD",
    currency_symbol: null,
  },
  {
    id: "150",
    country_name: "Nauru",
    country_code: "NR",
    dial_code: "+674",
    currency_name: null,
    currency_code: "AUD",
    currency_symbol: null,
  },
  {
    id: "151",
    country_name: "Nepal",
    country_code: "NP",
    dial_code: "+977",
    currency_name: null,
    currency_code: "NPR",
    currency_symbol: null,
  },
  {
    id: "152",
    country_name: "Netherlands",
    country_code: "NL",
    dial_code: "+31",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "153",
    country_name: "Netherlands Antilles",
    country_code: "AN",
    dial_code: "+599",
    currency_name: null,
    currency_code: "ANG",
    currency_symbol: null,
  },
  {
    id: "154",
    country_name: "New Caledonia",
    country_code: "NC",
    dial_code: "+687",
    currency_name: null,
    currency_code: "XPF",
    currency_symbol: null,
  },
  {
    id: "155",
    country_name: "New Zealand",
    country_code: "NZ",
    dial_code: "+64",
    currency_name: null,
    currency_code: "NZD",
    currency_symbol: null,
  },
  {
    id: "156",
    country_name: "Nicaragua",
    country_code: "NI",
    dial_code: "+505",
    currency_name: null,
    currency_code: "NIO",
    currency_symbol: null,
  },
  {
    id: "157",
    country_name: "Niger",
    country_code: "NE",
    dial_code: "+227",
    currency_name: null,
    currency_code: "XOF",
    currency_symbol: null,
  },
  {
    id: "158",
    country_name: "Nigeria",
    country_code: "NG",
    dial_code: "+234",
    currency_name: null,
    currency_code: "NGN",
    currency_symbol: null,
  },
  {
    id: "159",
    country_name: "Niue",
    country_code: "NU",
    dial_code: "+683",
    currency_name: null,
    currency_code: "NZD",
    currency_symbol: null,
  },
  {
    id: "160",
    country_name: "Norfolk Island",
    country_code: "NF",
    dial_code: "+672",
    currency_name: null,
    currency_code: "AUD",
    currency_symbol: null,
  },
  {
    id: "161",
    country_name: "North Korea, Democratic People's Republic of",
    country_code: "KP",
    dial_code: "+850",
    currency_name: null,
    currency_code: "KPW",
    currency_symbol: null,
  },
  {
    id: "162",
    country_name: "Northern Ireland",
    country_code: "GB",
    dial_code: "+44",
    currency_name: null,
    currency_code: "GBP",
    currency_symbol: null,
  },
  {
    id: "163",
    country_name: "Northern Mariana Islands",
    country_code: "MP",
    dial_code: "+1670",
    currency_name: null,
    currency_code: "USD",
    currency_symbol: null,
  },
  {
    id: "164",
    country_name: "Norway",
    country_code: "NO",
    dial_code: "+47",
    currency_name: null,
    currency_code: "NOK",
    currency_symbol: null,
  },
  {
    id: "165",
    country_name: "Oman",
    country_code: "OM",
    dial_code: "+968",
    currency_name: null,
    currency_code: "OMR",
    currency_symbol: null,
  },
  {
    id: "166",
    country_name: "Pakistan",
    country_code: "PK",
    dial_code: "+92",
    currency_name: null,
    currency_code: "PKR",
    currency_symbol: null,
  },
  {
    id: "167",
    country_name: "Palau",
    country_code: "PW",
    dial_code: "+680",
    currency_name: null,
    currency_code: "USD",
    currency_symbol: null,
  },
  {
    id: "168",
    country_name: "Palestinian Territory, Occupied",
    country_code: "PS",
    dial_code: "+970",
    currency_name: null,
    currency_code: "ILS",
    currency_symbol: null,
  },
  {
    id: "169",
    country_name: "Panama",
    country_code: "PA",
    dial_code: "+507",
    currency_name: null,
    currency_code: "PAB",
    currency_symbol: null,
  },
  {
    id: "170",
    country_name: "Papua New Guinea",
    country_code: "PG",
    dial_code: "+675",
    currency_name: null,
    currency_code: "PGK",
    currency_symbol: null,
  },
  {
    id: "171",
    country_name: "Paraguay",
    country_code: "PY",
    dial_code: "+595",
    currency_name: null,
    currency_code: "PYG",
    currency_symbol: null,
  },
  {
    id: "172",
    country_name: "Peru",
    country_code: "PE",
    dial_code: "+51",
    currency_name: null,
    currency_code: "PEN",
    currency_symbol: null,
  },
  {
    id: "173",
    country_name: "Philippines",
    country_code: "PH",
    dial_code: "+63",
    currency_name: null,
    currency_code: "PHP",
    currency_symbol: null,
  },
  {
    id: "174",
    country_name: "Pitcairn",
    country_code: "PN",
    dial_code: "+870",
    currency_name: null,
    currency_code: "NZD",
    currency_symbol: null,
  },
  {
    id: "175",
    country_name: "Poland",
    country_code: "PL",
    dial_code: "+48",
    currency_name: null,
    currency_code: "PLN",
    currency_symbol: null,
  },
  {
    id: "176",
    country_name: "Portugal",
    country_code: "PT",
    dial_code: "+351",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "177",
    country_name: "Puerto Rico",
    country_code: "PR",
    dial_code: "+1939",
    currency_name: null,
    currency_code: "USD",
    currency_symbol: null,
  },
  {
    id: "178",
    country_name: "Qatar",
    country_code: "QA",
    dial_code: "+974",
    currency_name: null,
    currency_code: "QAR",
    currency_symbol: null,
  },
  {
    id: "179",
    country_name: "R\u00e9union",
    country_code: "RE",
    dial_code: "+262",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "180",
    country_name: "Romania",
    country_code: "RO",
    dial_code: "+40",
    currency_name: null,
    currency_code: "RON",
    currency_symbol: null,
  },
  {
    id: "181",
    country_name: "Russia (Russian Federation)",
    country_code: "RU",
    dial_code: "+7",
    currency_name: null,
    currency_code: "RUB",
    currency_symbol: null,
  },
  {
    id: "182",
    country_name: "Rwanda",
    country_code: "RW",
    dial_code: "+250",
    currency_name: null,
    currency_code: "RWF",
    currency_symbol: null,
  },
  {
    id: "183",
    country_name: "Saint Helena, Ascension and Tristan Da Cunha",
    country_code: "SH",
    dial_code: "+290",
    currency_name: null,
    currency_code: "SHP",
    currency_symbol: null,
  },
  {
    id: "184",
    country_name: "Saint Kitts and Nevis",
    country_code: "KN",
    dial_code: "+1869",
    currency_name: null,
    currency_code: "XCD",
    currency_symbol: null,
  },
  {
    id: "185",
    country_name: "Saint Lucia",
    country_code: "LC",
    dial_code: "+1758",
    currency_name: null,
    currency_code: "XCD",
    currency_symbol: null,
  },
  {
    id: "186",
    country_name: "Saint Pierre and Miquelon",
    country_code: "PM",
    dial_code: "+508",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "187",
    country_name: "Saint Vincent and the Grenadines",
    country_code: "VC",
    dial_code: "+1784",
    currency_name: null,
    currency_code: "XCD",
    currency_symbol: null,
  },
  {
    id: "188",
    country_name: "Samoa",
    country_code: "WS",
    dial_code: "+685",
    currency_name: null,
    currency_code: "WST",
    currency_symbol: null,
  },
  {
    id: "189",
    country_name: "San Marino",
    country_code: "SM",
    dial_code: "+378",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "190",
    country_name: "Sao Tome and Principe",
    country_code: "ST",
    dial_code: "+239",
    currency_name: null,
    currency_code: "STD",
    currency_symbol: null,
  },
  {
    id: "191",
    country_name: "Saudi Arabia",
    country_code: "SA",
    dial_code: "+966",
    currency_name: null,
    currency_code: "SAR",
    currency_symbol: null,
  },
  {
    id: "192",
    country_name: "Scotland",
    country_code: "GB",
    dial_code: "+44",
    currency_name: null,
    currency_code: "GBP",
    currency_symbol: null,
  },
  {
    id: "193",
    country_name: "Senegal",
    country_code: "SN",
    dial_code: "+221",
    currency_name: null,
    currency_code: "XOF",
    currency_symbol: null,
  },
  {
    id: "194",
    country_name: "Serbia",
    country_code: "RS",
    dial_code: "+381",
    currency_name: null,
    currency_code: "RSD",
    currency_symbol: null,
  },
  {
    id: "195",
    country_name: "Seychelles",
    country_code: "SC",
    dial_code: "+248",
    currency_name: null,
    currency_code: "SCR",
    currency_symbol: null,
  },
  {
    id: "196",
    country_name: "Sierra Leone",
    country_code: "SL",
    dial_code: "+232",
    currency_name: null,
    currency_code: "SLL",
    currency_symbol: null,
  },
  {
    id: "197",
    country_name: "Singapore",
    country_code: "SG",
    dial_code: "+65",
    currency_name: null,
    currency_code: "SGD",
    currency_symbol: null,
  },
  {
    id: "198",
    country_name: "Slovakia",
    country_code: "SK",
    dial_code: "+421",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "199",
    country_name: "Slovenia",
    country_code: "SI",
    dial_code: "+386",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "200",
    country_name: "Solomon Islands",
    country_code: "SB",
    dial_code: "+677",
    currency_name: null,
    currency_code: "SBD",
    currency_symbol: null,
  },
  {
    id: "201",
    country_name: "Somalia",
    country_code: "SO",
    dial_code: "+252",
    currency_name: null,
    currency_code: "SOS",
    currency_symbol: null,
  },
  {
    id: "202",
    country_name: "South Africa",
    country_code: "ZA",
    dial_code: "+27",
    currency_name: null,
    currency_code: "ZAR",
    currency_symbol: null,
  },
  {
    id: "203",
    country_name: "South Georgia and the South Sandwich Islands",
    country_code: "GS",
    dial_code: "+500",
    currency_name: null,
    currency_code: "GBP",
    currency_symbol: null,
  },
  {
    id: "204",
    country_name: "South Korea, Republic of Korea",
    country_code: "KR",
    dial_code: "+82",
    currency_name: null,
    currency_code: "KRW",
    currency_symbol: null,
  },
  {
    id: "205",
    country_name: "South Sudan",
    country_code: "SS",
    dial_code: "+211",
    currency_name: null,
    currency_code: "SSP",
    currency_symbol: null,
  },
  {
    id: "206",
    country_name: "Spain",
    country_code: "ES",
    dial_code: "+34",
    currency_name: null,
    currency_code: "EUR",
    currency_symbol: null,
  },
  {
    id: "207",
    country_name: "Sri Lanka",
    country_code: "LK",
    dial_code: "+94",
    currency_name: null,
    currency_code: "LKR",
    currency_symbol: null,
  },
  {
    id: "208",
    country_name: "Sudan",
    country_code: "SD",
    dial_code: "+249",
    currency_name: null,
    currency_code: "SDG",
    currency_symbol: null,
  },
  {
    id: "209",
    country_name: "Suriname",
    country_code: "SR",
    dial_code: "+597",
    currency_name: null,
    currency_code: "SRD",
    currency_symbol: null,
  },
  {
    id: "210",
    country_name: "Svalbard and Jan Mayen",
    country_code: "SJ",
    dial_code: "+47",
    currency_name: null,
    currency_code: "NOK",
    currency_symbol: null,
  },
  {
    id: "211",
    country_name: "Swaziland",
    country_code: "SZ",
    dial_code: "+268",
    currency_name: null,
    currency_code: "SZL",
    currency_symbol: null,
  },
  {
    id: "212",
    country_name: "Sweden",
    country_code: "SE",
    dial_code: "+46",
    currency_name: null,
    currency_code: "SEK",
    currency_symbol: null,
  },
  {
    id: "213",
    country_name: "Switzerland",
    country_code: "CH",
    dial_code: "+41",
    currency_name: null,
    currency_code: "CHF",
    currency_symbol: null,
  },
  {
    id: "214",
    country_name: "Syria (Syrian Arab Republic)",
    country_code: "SY",
    dial_code: "+963",
    currency_name: null,
    currency_code: "SYP",
    currency_symbol: null,
  },
  {
    id: "215",
    country_name: "Taiwan",
    country_code: "TW",
    dial_code: "+886",
    currency_name: null,
    currency_code: "TWD",
    currency_symbol: null,
  },
  {
    id: "216",
    country_name: "Tajikistan",
    country_code: "TJ",
    dial_code: "+992",
    currency_name: null,
    currency_code: "TJS",
    currency_symbol: null,
  },
  {
    id: "217",
    country_name: "Tanzania, United Republic of",
    country_code: "TZ",
    dial_code: "+255",
    currency_name: null,
    currency_code: "TZS",
    currency_symbol: null,
  },
  {
    id: "218",
    country_name: "Thailand",
    country_code: "TH",
    dial_code: "+66",
    currency_name: null,
    currency_code: "THB",
    currency_symbol: null,
  },
  {
    id: "219",
    country_name: "Timor-Leste",
    country_code: "TL",
    dial_code: "+670",
    currency_name: null,
    currency_code: "USD",
    currency_symbol: null,
  },
  {
    id: "220",
    country_name: "Togo",
    country_code: "TG",
    dial_code: "+228",
    currency_name: null,
    currency_code: "XOF",
    currency_symbol: null,
  },
  {
    id: "221",
    country_name: "Tokelau",
    country_code: "TK",
    dial_code: "+690",
    currency_name: null,
    currency_code: "NZD",
    currency_symbol: null,
  },
  {
    id: "222",
    country_name: "Tonga",
    country_code: "TO",
    dial_code: "+676",
    currency_name: null,
    currency_code: "TOP",
    currency_symbol: null,
  },
  {
    id: "223",
    country_name: "Trinidad and Tobago",
    country_code: "TT",
    dial_code: "+1868",
    currency_name: null,
    currency_code: "TTD",
    currency_symbol: null,
  },
  {
    id: "224",
    country_name: "Tunisia",
    country_code: "TN",
    dial_code: "+216",
    currency_name: null,
    currency_code: "TND",
    currency_symbol: null,
  },
  {
    id: "225",
    country_name: "Turkey",
    country_code: "TR",
    dial_code: "+90",
    currency_name: null,
    currency_code: "TRY",
    currency_symbol: null,
  },
  {
    id: "226",
    country_name: "Turkmenistan",
    country_code: "TM",
    dial_code: "+993",
    currency_name: null,
    currency_code: "TMT",
    currency_symbol: null,
  },
  {
    id: "227",
    country_name: "Turks and Caicos Islands",
    country_code: "TC",
    dial_code: "+1649",
    currency_name: null,
    currency_code: "USD",
    currency_symbol: null,
  },
  {
    id: "228",
    country_name: "Tuvalu",
    country_code: "TV",
    dial_code: "+688",
    currency_name: null,
    currency_code: "AUD",
    currency_symbol: null,
  },
  {
    id: "229",
    country_name: "Uganda",
    country_code: "UG",
    dial_code: "+256",
    currency_name: null,
    currency_code: "UGX",
    currency_symbol: null,
  },
  {
    id: "230",
    country_name: "Ukraine",
    country_code: "UA",
    dial_code: "+380",
    currency_name: null,
    currency_code: "UAH",
    currency_symbol: null,
  },
  {
    id: "231",
    country_name: "United Arab Emirates",
    country_code: "AE",
    dial_code: "+971",
    currency_name: null,
    currency_code: "AED",
    currency_symbol: null,
  },
  {
    id: "232",
    country_name: "United Kingdom",
    country_code: "GB",
    dial_code: "+44",
    currency_name: null,
    currency_code: "GBP",
    currency_symbol: null,
  },
  {
    id: "233",
    country_name: "United States",
    country_code: "US",
    dial_code: "+1",
    currency_name: null,
    currency_code: "USD",
    currency_symbol: null,
  },
  {
    id: "234",
    country_name: "United States Minor Outlying Islands",
    country_code: "UM",
    dial_code: "+1581",
    currency_name: null,
    currency_code: "USD",
    currency_symbol: null,
  },
  {
    id: "235",
    country_name: "Uruguay",
    country_code: "UY",
    dial_code: "+598",
    currency_name: null,
    currency_code: "UYU",
    currency_symbol: null,
  },
  {
    id: "236",
    country_name: "Uzbekistan",
    country_code: "UZ",
    dial_code: "+998",
    currency_name: null,
    currency_code: "UZS",
    currency_symbol: null,
  },
  {
    id: "237",
    country_name: "Vanuatu",
    country_code: "VU",
    dial_code: "+678",
    currency_name: null,
    currency_code: "VUV",
    currency_symbol: null,
  },
  {
    id: "238",
    country_name: "Venezuela, Bolivarian Republic of",
    country_code: "VE",
    dial_code: "+58",
    currency_name: null,
    currency_code: "VEF",
    currency_symbol: null,
  },
  {
    id: "239",
    country_name: "Vietnam",
    country_code: "VN",
    dial_code: "+84",
    currency_name: null,
    currency_code: "VND",
    currency_symbol: null,
  },
  {
    id: "240",
    country_name: "Virgin Islands, British",
    country_code: "VG",
    dial_code: "+1284",
    currency_name: null,
    currency_code: "USD",
    currency_symbol: null,
  },
  {
    id: "241",
    country_name: "Virgin Islands, U.S.",
    country_code: "VI",
    dial_code: "+1340",
    currency_name: null,
    currency_code: "USD",
    currency_symbol: null,
  },
  {
    id: "242",
    country_name: "Wales",
    country_code: "GB",
    dial_code: "+44",
    currency_name: null,
    currency_code: "GBP",
    currency_symbol: null,
  },
  {
    id: "243",
    country_name: "Wallis and Futuna",
    country_code: "WF",
    dial_code: "+681",
    currency_name: null,
    currency_code: "XPF",
    currency_symbol: null,
  },
  {
    id: "244",
    country_name: "Western Sahara",
    country_code: "EH",
    dial_code: "+732",
    currency_name: null,
    currency_code: "MAD",
    currency_symbol: null,
  },
  {
    id: "245",
    country_name: "Yemen",
    country_code: "YE",
    dial_code: "+967",
    currency_name: null,
    currency_code: "YER",
    currency_symbol: null,
  },
  {
    id: "246",
    country_name: "Zambia",
    country_code: "ZM",
    dial_code: "+260",
    currency_name: null,
    currency_code: "ZMW",
    currency_symbol: null,
  },
  {
    id: "247",
    country_name: "Zimbabwe",
    country_code: "ZW",
    dial_code: "+263",
    currency_name: null,
    currency_code: "ZWD",
    currency_symbol: null,
  },
];
